### PR TITLE
Add u-boot blob and patch for s905x3 boxes

### PR DESCRIPTION
**Pull request by sandyiscool**
The blob is built on mainline u-boot's tag v2023.10.

This u-boot can boot the plain Image kernel format adopted by the Armbian build system starting from 23.05 releases, on s905x3 based boxes.

### CODE REVIEW

**Review by SteeManMI — COMMENTED** [review]
First off, I want to apologize for taking so long to review.  In the future to avoid me as a bottleneck, feel free to submit the PR directly to armbian main.

Second, a very minor fix.  Since you are adding the s905x3 section to the3 readme, you should also remove the TODO comment for the same.

Now the bigger issue.  If I try to follow the instructions you added to the readme, it fails for me.  I get the following errors upon applying the patch to the u-boot tree:

blind@xps13:~/work/u-boot$ git status
HEAD detached at v2020.07
nothing to commit, working tree clean
blind@xps13:~/work/u-boot$ patch -p1 < /home/blind/Downloads/u-boot-s905x3.patch 
patching file arch/arm/dts/meson-sm1-sei610.dts
patching file configs/sei610_defconfig
Hunk #1 FAILED at 14.
Hunk #2 FAILED at 43.
Hunk #3 FAILED at 67.
Hunk #4 FAILED at 94.
4 out of 4 hunks FAILED -- saving rejects to file configs/sei610_defconfig.rej
patching file include/configs/sei610.h
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file include/configs/sei610.h.rej


I'm guessing you perhaps developed your patch against a different u-boot branch than you put in the readme?

If you can tix up these issues, please resubmit the PR against armbian main, and I'll test there and get this in.

Note: I didn't actually test your u-boot binary, since I wanted to rebuild from the instructions and see that I got the same result as you.

**Comment by SteeManMI** [comment]
Now I just read your commit message, and see that you indeed did this against a different u-boot branch than you have in the instructions.  I will continue testing with that knowledge.  So it looks like just a couple of quick fixes to the readme instructions should complete this.

**Comment by sandyiscool** [comment]
I am honestly sorry about the oversight. I should have updated the readme with the correct tag to be checked out before applying the patch. In my excitement to get the PR out, I missed it completely. Thanks for checking it and letting me know. I will update the PR.

No issues on the delay. I understand. I did think that may be I should close this PR and open it in the Armbian main repo so that it will be easier for you and others to look at; given that it has a lots of eyes to review PRs. I will keep this in mind in future.

**Comment by SteeManMI** [comment]
Once I pulled the correct uboot branch, everything built fine and tested out fine (although I had a bad SD card that caused me to waste a lot of time, before I figured out the issue was the sd card, not the build that I was testing).  So lets close this PR, and take what you have and raise a PR again Armbian main.

**Comment by SteeManMI** [comment]
Please go ahead, if I wasn't clear, and raise a PR against armbian main.  I'll approve and get this in to the 24.02 release.

**Comment by SteeManMI** [comment]
One more thing, If you could enable CONFIG_DISPLAY_BOARDINFO_LATE=y in your PR when submitted that would be good.  This delays the output of the u-boot version and board info until the hdmi output is enabled, so that information appears to the end user.  Sorry I didn't catch this earlier.

**Comment by sandyiscool** [comment]
Sorry, I have been traveling hence could not follow up on creating a PR on the main armbian repo earlier. I will do it shortly.
Sure, I will add the config CONFIG_DISPLAY_BOARDINFO_LATE=y.

Also, because I will be rebuilding the blob (with config CONFIG_DISPLAY_BOARDINFO_LATE=y) and adding it to the PR as well, would you mind testing the blob  just to confirm that everything works fine with uboot ? I am remote and unable to check on my board right now.

**Comment by sandyiscool** [comment]
I have invited you to my not-yet-public git hub repo https://github.com/sandyiscool/amlogic-uboot-build
I use this to build the u-boot blob. You can view the github actions run and verify the fingerprint of the blob that I will be adding to the PR.

**Comment by sandyiscool** [comment]
I have created the PR on main armbian repo: https://github.com/armbian/build/pull/6215

Kindly review when you get some time to look at it.

**Pull request closed without merging**
